[package]
name = "what-time"
version.workspace = true
description = "A compact neural parser for English schedules"
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
jiff = { workspace = true }
wgpu = { workspace = true, optional = true }
pollster = { workspace = true, optional = true }
bytemuck = { workspace = true, optional = true }

[features]
gpu = ["dep:wgpu", "dep:pollster", "dep:bytemuck"]
