// Generates src/version.ts from package.json so the exported VERSION can
// never drift from the published version. Run by `pnpm build`.
import { readFileSync, writeFileSync } from "node:fs";
const version = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8")).version;
writeFileSync(
  new URL("../src/version.ts", import.meta.url),
  `// Generated by pnpm build from package.json — do not edit.\nexport const VERSION = "${version}";\n`,
);
